export const locators = {
  productLabel: `Add to cart: “Remax Armor Serija Data Kablo 2,4A Type C Rc116 A”`,
  cartLabel: `Dodaj u košaricu`,
  paymentButton: `Kreni na plaćanje`,
  removeProductButton: `Ukloni Xiaomi Redmi 12 (4/128) iz košarice`,
  alertMessage: `“Xiaomi Redmi 12 (4/128)” uklonjeno.`,
  remove: `xpath=/html/body/div[2]/div[6]/div/div[2]/div/main/div/div/div/section/form/table/tbody/tr[1]/td[1]/a`,
  name: "#billing_first_name",
  lastname: "#billing_last_name",
  country: "#billing_country",
  street: "#billing_address_1",
  postalCode: "#billing_postcode",
  city: "#billing_city",
  phone: "#billing_phone",
  email: "#billing_email",
  shipping: "#shipping_method_0_local_pickup3",
  payment: "#payment_method_bacs",
  orderButton: "#place_order",
  //firstProduct: `xpath=//*[@id="post-7105"]/div/div/section[16]/div/div/div/div/div/div/div/ul/li[3]/div[2]/a`,
  //colorSelect: `xpath=//*[@id="sticky-scroll"]/div/table/tbody/tr[2]/td/div[1]/ul/li[1]/button`,
  //memorySelect: `xpath=//*[@id="sticky-scroll"]/div/table/tbody/tr[1]/td/div[1]/ul/li[2]/button`,
  //price: `xpath=//*[@id="post-9"]/div/div/section/form/table/tbody/tr[1]/td[6]/span/bdi`,
};
